version: "3.9"
services:
  postgres:
      image: postgres:16-bullseye
      restart: always
      env_file:
        - pg.env
      volumes:
        - ../postgresql_data:/var/lib/postgresql/data
      ports:
        - "5433:5432"
  backend:
    depends_on:
      - postgres
    build: .
    restart: always
    env_file:
        - backend.env
    volumes:
        - ../assets:/app/dist/src/images
        - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "4030:4000"
  client:
    depends_on:
      - backend
    build: ../client
    env_file:
        - ../client/.env
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"