version: "3.9"
services:
  postgres:
      image: postgres:16-bullseye
      restart: always
      environment:
        - POSTGRES_DB=vkuseda_db
        - POSTGRES_PASSWORD=Admin123
        - POSTGRES_USER=postgres
      ports:
        - "5432:5432"
  backend:
    depends_on:
      - postgres
    build: .
    restart: always
    environment:
      - DB_NAME=vkuseda_db
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Admin123
    ports:
      - "4000:4000"