version: "3.9"
services:
  postgres:
      image: postgres:16-bullseye
      restart: always
      environment:
        - POSTGRES_DB=
        - POSTGRES_PASSWORD=
        - POSTGRES_USER=
      volumes:
        - ../postgresql_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
  backend:
    depends_on:
      - postgres
    build: .
    restart: always
    environment:
      - DB_NAME=
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=
      - DB_PASSWORD=
    volumes:
        - ../assets:/app/dist/src/images
    ports:
      - "4030:4000"