version: "3.9"
services:
  postgres:
      container_name: project_db
      image: postgres:16.1
      restart: always
      environment:
        - POSTGRES_DB=
        - POSTGRES_PASSWORD=
        - POSTGRES_USER=
      ports:
        - "5432:5432"
  server:
    container_name: backend
    depends_on:
      - postgres
    build:
      context: .
    environment:
      - DB_NAME=
      - DB_HOST=
      - DB_PORT=
      - DB_USER=
      - DB_PASSWORD=
    ports:
      - "3000:3000"